export const colors = {
  white: "var(--bg-white)",
  blue: "var(--bg-blue-600)",
  sky: "var(--bg-sky-600)",
  indigo: "var(--bg-indigo-600)",
  violet: "var(--bg-violet-600)",
  cyan: "var(--bg-cyan-600)",
  fuchsia: "var(--bg-fuchsia-600)",
  green: "var(--bg-green-600)",
  emerald: "var(--bg-emerald-600)",
  teal: "var(--bg-teal-600)",
  purple: "var(--bg-purple-600)",
  orange: "var(--bg-orange-600)",
  amber: "var(--bg-amber-600)",
  yellow: "var(--bg-yellow-600)",
  lime: "var(--bg-lime-600)",
  pink: "var(--bg-pink-600)",
  rose: "var(--bg-rose-600)",
  slate: "var(--bg-slate-600)",
  red: "var(--bg-red-600)",
  gray: "var(--bg-gray-600)",
  zinc: "var(--bg-zinc-600)",
  stone: "var(--bg-stone-600)",
  dark: "var(--bg-dark)",
  black: "var(--bg-black)",
}
export type Color = keyof typeof colors
